var AppSettings =
{
    ActionsUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/CTSActions.svc/json/",
    AddressBookUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/AddressBookActions.svc/json/",
    AdminUrl: "http://ctsbdemo.intalio.com/CTSAdmin/Login_Form.aspx",
    AsposeLicenseFile: "C:\\Program Files\\Ever Team\\CTSHTML5\\CTSFolders\\Aspose\\Aspose.Total.Product.Family.lic",
    AuthenticationUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/Authentication.svc/json/",
    BAMReportsUrl: "http://ctsbdemo.intalio.com/CTSCHARTS/Default.html",
    BAMUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/BAM.svc/json/",
    barcodeUrl: "http://ctsbdemo.intalio.com/CTSWEB/Style/5.4.1/EverteamTheme/Resources/barcode.jpeg",
    CMMSUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/CMMSActions.svc/json/",
    DMSUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/DMSActions.svc/json/",
    EnterpriseProject: "1",
    EverSuiteCoreUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/EverSuiteCore.svc/json/",
    FollowupUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/FollowupActions.svc/json/",
    GenericForms: "False",
    InboxActionsUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/InboxActions.svc/json/",
    JsonLength: "100000000",
    LocalRootPath: "http://ctsbdemo.intalio.com/CTSWEB",
    loginImage: "LoginImage.png",
    LoginLogo: "LoginLogo.png",
    LogoImageName: "Intalio-Logo-Black-Color.png",
    LogoText: "",
    LogoType: "image",
    OldLoginPage: "false",
    ReportChartUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/ReportChart.svc/json/",
    ReportsActionsUrl: "http://ctsbdemo.intalio.com/Services/Connector/api/ReportsActions.svc/json/",
    ReportsFolder: "BlueCTS",
    ReportsServerUrl: "http://etgs-presales/Reportserver_SQL14/",
    ReportUrl: "http://ctsbdemo.intalio.com/CTSReports/Templates/ReportForms/Reports.aspx",
    ShowStructureCode: "false",
    StyleFolderName: "EverteamTheme",
    TempFolder: "C:\Program Files\Ever Team\CTSHTML5\CTSFolders\Temppath",
    ViewerUrl: "/_layouts/15/EverSuite.Viewer/EverSuiteViewer.aspx?displaymode=fitwidth",
    VIPUrl: ""
};